# -*- coding: utf-8 -*-
"""Final_Realtime_sentiment_DE_EN_Niyathi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sStnBO3e61XexKnLREclxxnwTH9clJvY

# Real-Time Sentiment on German Amazon Reviews
**Student:** Niyathi Lekkala  
**Course:** Deep Learning — Final Project  
**Runtime:** Google Colab (GPU recommended)

## Abstract
I build a sentiment classifier for German Amazon reviews, comparing a classical baseline (TF-IDF + Logistic Regression) with a multilingual Transformer (XLM-RoBERTa). I map 1–5 stars → sentiment: negative (1–2), neutral (3), positive (4–5), report Accuracy & Macro-F1, visualize confusion matrices, and provide an inference helper suitable for a simple real-time demo.

## 1) Setup
Install pinned library versions and import core modules.
"""

# %%capture
!pip -q install "transformers<5" "datasets<3" accelerate sentencepiece \
                scikit-learn matplotlib seaborn pandas joblib torch

# ---- Imports (all in one place) ----
import os, random, json, pathlib
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (classification_report, confusion_matrix,
                             accuracy_score, f1_score,precision_recall_curve, average_precision_score)
from sklearn.preprocessing import label_binarize

import torch, transformers
from datasets import load_dataset, Dataset, DatasetDict
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,pipeline,
                          TrainingArguments, Trainer, TextClassificationPipeline)

import ipywidgets as widgets
from IPython.display import display
from sklearn.calibration import calibration_curve
import time


# visuals + style
sns.set_context("talk")

# Reproducibility
SEED = 42
random.seed(SEED); np.random.seed(SEED); os.environ["PYTHONHASHSEED"] = str(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)

# Quiet down W&B
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "disabled"

print("Transformers:", transformers.__version__, "| Datasets pinned <3: OK")
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

# Helper
from pathlib import Path
import matplotlib.pyplot as plt
FIGDIR = Path("figures"); FIGDIR.mkdir(exist_ok=True)

def savefig(name):
    path = FIGDIR / f"{name}.png"
    plt.tight_layout()
    plt.savefig(path, dpi=200, bbox_inches="tight")
    print("Saved:", path)

"""## (a) Data Analysis — Load Real Dataset
We use **Hugging Face Datasets**: `amazon_reviews_multi` (German split).  
No uploads/Drive needed. Splits provided: `train`, `validation`, `test`.

"""

de=pd.read_csv("amazon_reviews.csv")
de
display(de.head())
de.shape

"""## (b) Discover & Visualize
Normalize columns to `review_body` and `stars`, quick EDA: text length distribution, star histogram, and a few examples.

"""

csv_path = "amazon_reviews.csv"
df = pd.read_csv(csv_path)

text_col  = next((c for c in df.columns if c.lower() in ["review_body","review","text","reviewtext","content"]), None)
stars_col = next((c for c in df.columns if c.lower() in ["stars","rating","star_rating","overall"]), None)
assert text_col and stars_col, f"Couldn't find text/rating columns. Columns are: {list(df.columns)}"

df = df[[text_col, stars_col]].rename(columns={text_col:"review_body", stars_col:"stars"}).dropna()

# clean and keep valid star range
df["review_body"] = (df["review_body"].astype(str).str.replace(r"\s+"," ", regex=True).str.strip())
df["stars"] = pd.to_numeric(df["stars"], errors="coerce").round().astype(int)
df = df[df["stars"].between(1,5)].reset_index(drop=True)

# stratified split 70:15:15
train_df, temp_df = train_test_split(df, test_size=0.30, stratify=df["stars"], random_state=42)
val_df,   test_df = train_test_split(temp_df, test_size=0.50, stratify=temp_df["stars"], random_state=42)

for name, d in [("train",train_df),("val",val_df),("test",test_df)]:
    print(name, d.shape, d["stars"].value_counts().sort_index().to_dict())

"""## (c) Data Preprocessing — Label Mapping
Map stars → sentiment classes:
- 1–2 → **negative** (0)  
- 3   → **neutral**  (1)  
- 4–5 → **positive** (2)

"""

def stars_to_label(star: int) -> int:
    if star <= 2: return 0
    if star == 3: return 1
    return 2

for df in (train_df, val_df, test_df):
    df["label"] = df["stars"].astype(int).map(stars_to_label)

fig, ax = plt.subplots(1,3, figsize=(14,4))
for i,(name,df) in enumerate([("train",train_df),("val",val_df),("test",test_df)]):
    sns.countplot(x=df["label"], ax=ax[i]); ax[i].set_title(f"Labels in {name} (0=neg,1=neu,2=pos)")
plt.tight_layout(); plt.show()

train_df.head(3)

# FIGURE: Star distribution (Train)
fig, ax = plt.subplots(figsize=(6,4))
sns.countplot(x=train_df["stars"], ax=ax)
ax.set_title("Star Rating Distribution (Train)")
ax.set_xlabel("Stars"); ax.set_ylabel("Count")
savefig("Figure-EDA-Stars")
plt.show()

# FIGURE: Review length histogram (Train)
lens = train_df["review_body"].str.len()
fig, ax = plt.subplots(figsize=(6,4))
sns.histplot(lens, bins=60, ax=ax)
ax.set_title("Review Length (Characters) — Train")
ax.set_xlabel("Length"); ax.set_ylabel("Count")
savefig("Figure-EDA-Lengths")
plt.show()

"""## (d) Baseline Model — TF-IDF + Logistic Regression
I train on `train`, evaluate on `test`. This gives a fast, explainable reference to compare with the Transformer.

"""

X_train, y_train = train_df["review_body"], train_df["label"]
X_test,  y_test  = test_df["review_body"],  test_df["label"]

baseline = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=50_000, ngram_range=(1,2))),
    ("clf", LogisticRegression(max_iter=300, solver="lbfgs", random_state=42))
]).fit(X_train, y_train)

y_pred_base = baseline.predict(X_test)
print("Baseline — TF-IDF + LR")
print(classification_report(y_test, y_pred_base, digits=4))

sns.heatmap(confusion_matrix(y_test, y_pred_base, labels=[0,1,2]),
            annot=True, fmt="d", cmap="Blues",
            xticklabels=["neg","neu","pos"], yticklabels=["neg","neu","pos"])
plt.title("Baseline Confusion Matrix"); plt.xlabel("Pred"); plt.ylabel("True"); plt.show()

# earlier
X_test  = test_df["review_body"]
y_test  = test_df["label"]
y_pred_base = baseline.predict(X_test)

# FIGURE: Baseline confusion matrix (counts)
cm = confusion_matrix(y_test, y_pred_base, labels=[0,1,2])
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["neg","neu","pos"], yticklabels=["neg","neu","pos"])
plt.title("Baseline (TF-IDF + LR) — Confusion Matrix (Counts)")
plt.xlabel("Predicted"); plt.ylabel("True")
savefig("Figure-Baseline-CM-Counts")
plt.show()

# FIGURE: Baseline per-class PR curves (one-vs-rest)
proba_base = baseline.predict_proba(X_test)
Y = label_binarize(y_test, classes=[0,1,2])

fig, axes = plt.subplots(1,3, figsize=(14,4))
names = ["negative","neutral","positive"]
for i, name in enumerate(names):
    p, r, _ = precision_recall_curve(Y[:,i], proba_base[:,i])
    ap = average_precision_score(Y[:,i], proba_base[:,i])
    axes[i].plot(r, p)
    axes[i].set_title(f"Baseline PR — {name} (AP={ap:.3f})")
    axes[i].set_xlabel("Recall"); axes[i].set_ylabel("Precision")
savefig("Figure-Baseline-PR")
plt.show()

"""## (e) Deep Learning — XLM-RoBERTa (multilingual) Fine-Tuning
Tokenize with `xlm-roberta-base` and fine-tune a 3-class head.  
 sequence length 128, batch 8, 1 epoch.
I avoid eval-strategy API differences by evaluating explicitly after training.

"""

train_hf = Dataset.from_pandas(train_df[["review_body","label"]].reset_index(drop=True))
val_hf   = Dataset.from_pandas(val_df[["review_body","label"]].reset_index(drop=True))
test_hf  = Dataset.from_pandas(test_df[["review_body","label"]].reset_index(drop=True))
dset = DatasetDict({"train":train_hf, "validation":val_hf, "test":test_hf})

model_name = "xlm-roberta-base"
tok = AutoTokenizer.from_pretrained(model_name)

MAX_LEN = 128
def tokenize(batch):
    return tok(batch["review_body"], truncation=True, padding="max_length", max_length=MAX_LEN)

enc = dset.map(tokenize, batched=True)
enc = enc.remove_columns(["review_body"])
enc = enc.rename_column("label","labels")
enc.set_format("torch")

for split in ["train","validation","test"]:
    print(split, enc[split].column_names)

os.environ["WANDB_DISABLED"] = "true"; os.environ["WANDB_MODE"] = "disabled"

num_labels = 3
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

def compute_metrics_agnostic(p):
    logits = getattr(p, "predictions", p[0])
    labels = getattr(p, "label_ids",   p[1])
    preds  = np.argmax(logits, axis=1)
    return {"accuracy": accuracy_score(labels, preds),
            "f1_macro": f1_score(labels, preds, average="macro")}

args = TrainingArguments(
    output_dir="models/de_xlmr_fast",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_steps=100,
    report_to=[],
    fp16=bool(torch.cuda.is_available()),
    dataloader_num_workers=2,
    save_strategy="no",
    seed=42,
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=enc["train"],
    eval_dataset=enc["validation"],
    compute_metrics=compute_metrics_agnostic
)

trainer.train()
val_metrics  = trainer.evaluate(enc["validation"])
test_out     = trainer.predict(enc["test"])
print("Validation metrics:", val_metrics)
print("Test metrics:", test_out.metrics)

"""## (e) Confusion Matrix (DL)"""

y_true = test_out.label_ids
y_pred = test_out.predictions.argmax(axis=1)

cm = confusion_matrix(y_true, y_pred, labels=[0,1,2], normalize="true")
sns.heatmap(cm, annot=True, fmt=".2f", cmap="Greens",
            xticklabels=["neg","neu","pos"], yticklabels=["neg","neu","pos"])
plt.title("XLM-R (DE) Confusion Matrix — normalized"); plt.xlabel("Pred"); plt.ylabel("True"); plt.show()

print(classification_report(y_true, y_pred, digits=4,
                            target_names=["negative","neutral","positive"]))

# === Accuracy by text-length buckets ===
lens = np.array([len(t) for t in test_df["review_body"]])
bins = [0, 60, 120, 240, 10000]
labels = ["≤60", "61–120", "121–240", "≥241"]
bucket = pd.cut(lens, bins=bins, labels=labels, right=True)

acc_by_len = (pd.DataFrame({"bucket":bucket, "ok":(y_true==y_pred)})
                .groupby("bucket")["ok"].mean().reindex(labels))
acc_by_len.plot(kind="bar", figsize=(5,4))
plt.title("Accuracy by Review Length (XLM-R)"); plt.ylabel("accuracy")
savefig("Figure-XLMR-Acc-By-Length"); plt.show()

print(acc_by_len.to_frame("accuracy"))

proba_xlmr = torch.softmax(torch.tensor(test_out.predictions), dim=1).numpy()
Y = label_binarize(y_true, classes=[0,1,2])

fig, axes = plt.subplots(1,3, figsize=(14,4))
names = ["negative","neutral","positive"]
for i, name in enumerate(names):
    p, r, _ = precision_recall_curve(Y[:,i], proba_xlmr[:,i])
    ap = average_precision_score(Y[:,i], proba_xlmr[:,i])
    axes[i].plot(r, p)
    axes[i].set_title(f"XLM-R PR — {name} (AP={ap:.3f})")
    axes[i].set_xlabel("Recall"); axes[i].set_ylabel("Precision")
savefig("Figure-XLMR-PR")
plt.show()

"""Confidence tends to be [conservative/overconfident]; the reliability curve shows [under/over]-prediction above 0.8. This informs thresholding and alerting in a real-time dashboard."""

# === Confidence histogram + Reliability diagram ===

# probabilities from logits (already computed as proba_xlmr)
conf = proba_xlmr.max(axis=1)            # model confidence per sample
correct = (y_pred == y_true).astype(int)

# Confidence histogram
plt.figure(figsize=(5,4))
plt.hist(conf, bins=20)
plt.title("Prediction Confidence Histogram (XLM-R)"); plt.xlabel("max prob"); plt.ylabel("count")
savefig("Figure-XLMR-Confidence-Hist"); plt.show()

# Reliability (ECE-like) curve (one-vs-all average)
# bin predictions and compute avg accuracy per bin
prob_true, prob_pred = calibration_curve(correct, conf, n_bins=10, strategy="uniform")
plt.figure(figsize=(5,4))
plt.plot(prob_pred, prob_true, marker="o")
plt.plot([0,1],[0,1],"--",alpha=.5)
plt.title("Reliability Curve (XLM-R)"); plt.xlabel("Predicted prob"); plt.ylabel("Observed accuracy")
savefig("Figure-XLMR-Reliability"); plt.show()

id2lbl = {0:"negative",1:"neutral",2:"positive"}

err_idx = np.where(y_true != y_pred)[0][:8]  # first 8 errors
for i in err_idx:
    print("="*80)
    print("TRUE:", id2lbl[int(y_true[i])], "| PRED:", id2lbl[int(y_pred[i])])
    txt = test_df["review_body"].iloc[i]
    print(txt if len(txt)<600 else txt[:600]+" ...")

"""## Real-Time Inference Helper
Wraping this in a simple UI/API and log `{text, lang, sentiment, confidence, time}` to a DB.

"""

infer_pipe = TextClassificationPipeline(model=trainer.model, tokenizer=tok,
                                        return_all_scores=True, truncation=True, max_length=128)

def predict_sentiment(text: str):
    id2lbl = {0:"negative", 1:"neutral", 2:"positive"}
    scores = infer_pipe(text)[0]
    best = max(enumerate(scores), key=lambda x: x[1]["score"])
    return {"label_id": best[0], "label": id2lbl[best[0]], "confidence": float(best[1]["score"])}

print(predict_sentiment("Die Lieferung war sehr schnell und das Produkt ist top."))
print(predict_sentiment("Qualität schlecht, nach zwei Tagen kaputt gegangen."))

# === Latency benchmark (batch=1, avg over 50) ===
infer_pipe = TextClassificationPipeline(model=trainer.model, tokenizer=tok,
                                        return_all_scores=False, truncation=True, max_length=128)

texts = test_df["review_body"].sample(64, random_state=42).tolist()
def time_pipeline(pipe, texts, warmup=10, runs=50):
    for t in texts[:warmup]: _ = pipe(t)
    t0 = time.time()
    for t in texts[:runs]: _ = pipe(t)
    return (time.time() - t0)/runs

lat_ms = 1000 * time_pipeline(infer_pipe, texts)
plt.figure(figsize=(4,4))
plt.bar(["XLM-R (this device)"], [lat_ms])
plt.ylabel("ms / sample"); plt.title("Latency (batch=1, avg over 50)")
savefig("Figure-Latency-Bar"); plt.show()
print(f"Avg latency: {lat_ms:.1f} ms/sample")

"""I keep classification in German to avoid translation artifacts; English gloss is for readability.

## (f) Summary
**Baseline (TF-IDF + LR)**  
- Accuracy: 0.6071    
- Macro-F1: 0.4976

**XLM-RoBERTa (fine-tuned)**  
- Accuracy: 0.7418  
- Macro-F1: 0.6608

**Observations:**  
- Transformer improves Macro-F1 over baseline, indicating better balance across classes.  
- Typical confusions: neutral vs positive on short praise; negative vs neutral when wording is mild.

### Display-only translation for UI (DE→EN)
I keep the *classification* pipeline in German (XLM-RoBERTa fine-tuned on DE).
For readability only, I translate the input text to English using MarianMT
(`Helsinki-NLP/opus-mt-de-en`) and show: German text, English gloss, predicted label,
and confidence. Translation does **not** affect the label; it is for display only.
"""

# Translation pipeline (DE -> EN) for DISPLAY ONLY
trans_pipe = pipeline("translation", model="Helsinki-NLP/opus-mt-de-en")

# Sentiment inference pipeline (uses your fine-tuned model + tokenizer)
infer_pipe = TextClassificationPipeline(
    model=trainer.model,
    tokenizer=tok,
    return_all_scores=True,
    truncation=True,
    max_length=128
)

id2lbl = {0: "negative", 1: "neutral", 2: "positive"}

"""The model’s most-confident errors are typically neutral↔positive (short generic praise) and negative↔neutral (polite complaints)."""

# === Most-confident wrong predictions (top 10) ===
pred_conf = proba_xlmr[np.arange(len(proba_xlmr)), y_pred]
wrong = np.where(y_true != y_pred)[0]
wrong_sorted = wrong[np.argsort(-pred_conf[wrong])]
pick = wrong_sorted[:10]

id2lbl = {0:"negative",1:"neutral",2:"positive"}
rows=[]
for i in pick:
    rows.append({
        "Conf": f"{pred_conf[i]:.3f}",
        "True": id2lbl[int(y_true[i])],
        "Pred": id2lbl[int(y_pred[i])],
        "German review": test_df["review_body"].iloc[i][:220] + ("..." if len(test_df["review_body"].iloc[i])>220 else "")
    })
err_conf_df = pd.DataFrame(rows)
display(err_conf_df)
Path("artifacts").mkdir(exist_ok=True)
err_conf_df.to_csv("artifacts/most_confident_wrongs.csv", index=False)
print("Saved: artifacts/most_confident_wrongs.csv")

def predict_sentiment(text_de: str):
    scores = infer_pipe(text_de)[0]  # list of dicts: [{'label': 'LABEL_0', 'score': ...}, ...]
    # Map back to ids using model order
    # scores are already in label order (0..2) for HF classification heads
    best_idx = max(range(len(scores)), key=lambda i: scores[i]["score"])
    return {
        "label_id": best_idx,
        "label": id2lbl[best_idx],
        "confidence": float(scores[best_idx]["score"])
    }

def preview(text_de: str, add_time: bool = True, translate: bool = True):
    out = {"de": text_de}
    if translate:
        en = trans_pipe(text_de, max_length=256)[0]["translation_text"]
        out["en"] = en  # display-only gloss
    pred = predict_sentiment(text_de)
    out.update(pred)
    if add_time:
        out["time"] = datetime.utcnow().isoformat() + "Z"
    return out

samples = [
    "Die Batterie hält kaum einen Tag.",
    "Qualität okay, nichts Besonderes.",
    "Absolut begeistert – würde wieder kaufen!"
]
for t in samples:
    print(preview(t))

"""#requirements.txt

transformers<5

datasets<3

accelerate

sentencepiece

scikit-learn

matplotlib

seaborn

pandas

torch

joblib

## Real-Time Considerations — Clarification
This project **did not** implement a dashboard or API.  
Implemented: model training, evaluation (Accuracy & Macro-F1), confusion matrix/PR curves, and **single-sample latency** measurement to assess feasibility.  
Future work: expose an API and log to a DB to power a dashboard.
"""

def predict_sentiment_text(text_de: str):
    model.eval()
    enc = tok(text_de, return_tensors="pt", truncation=True, max_length=128).to(device)
    with torch.no_grad():
        logits = model(**enc).logits
        probs = torch.softmax(logits, dim=1).squeeze().cpu().numpy()
    pred = int(probs.argmax())
    id2lbl = {0:"negative", 1:"neutral", 2:"positive"}
    return {"label": id2lbl[pred], "confidence": float(probs[pred])}

samples = [
    "Die Batterie hält kaum einen Tag.",
    "Qualität okay, nichts Besonderes.",
    "Absolut begeistert – würde wieder kaufen!"
]
for s in samples:
    print(s, "->", predict_sentiment_text(s))

id2lbl = {0:"negative",1:"neutral",2:"positive"}

def predict_sentiment_text(text_de: str):
    model.eval()
    enc = tok(text_de, return_tensors="pt", truncation=True, max_length=128).to(model.device)
    with torch.no_grad():
        logits = model(**enc).logits
        probs = torch.softmax(logits, dim=1).squeeze().cpu().numpy()
    pred = int(np.argmax(probs))
    return id2lbl[pred], float(probs[pred])

inp = widgets.Textarea(
    value="Die Lieferung war sehr schnell und das Produkt ist top.",
    description="German review:",
    layout=widgets.Layout(width="100%", height="90px")
)
out = widgets.Output()

def on_click(_):
    with out:
        out.clear_output()
        lab, conf = predict_sentiment_text(inp.value)
        print(f"Label: {lab} | Confidence: {conf:.2f}")

btn = widgets.Button(description="Analyze")
btn.on_click(on_click)

display(inp, btn, out)

